language: php

services:
  - mysql

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer require satooshi/php-coveralls:dev-master -n
  - composer install -n
  - mysql -e 'CREATE DATABASE IF NOT EXISTS magento;'
  - vendor/bin/phinx migrate

script:
  - sh ./run_tests.sh

after_script:
  - php vendor/bin/coveralls -v