language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer require satooshi/php-coveralls:dev-master -n
  - composer install -n

script:
  - sh ./run_tests.sh

after_script:
  - php vendor/bin/coveralls -v